# This is a basic workflow to help you get started with Actions

name: Azure Machine Learning CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azureml-sdk

    - name: Train Model
      run: |
        az ml workspace show -w <your-workspace-name> -g <your-resource-group>
        python train.py

    - name: Deploy Model
      run: |
        az ml model register --model-path <model-path> --model-name <model-name>
        az ml model deploy --model-name <model-name> --service-name <service-name>
